---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

# kubelet fails even if ansible_swaptotal_mb = 0
- name: check swap
  command: /sbin/swapon -s
  register: swapon
  changed_when: no

- name: Disable swap
  command: /sbin/swapoff -a
  when: swapon.stdout
  ignore_errors: True

- name: add Kubernetes repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes yum repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: install kubernetes binaries
  yum:
    name: "{{ packages }}"
  vars:
    version: 1.17.2
    packages:
    - "kubelet-{{ version }}"
    - "kubeadm-{{ version }}"
    - "kubectl-{{ version}}"
